import type { Metadata } from "next";
import { Bebas_Neue, Bree_Serif, Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { VisualEditing } from "next-sanity/visual-editing";
import { SanityLive } from "@/sanity/lib/live";
import { draftMode } from "next/headers";
import { DisableDraftMode } from "@/components/disable-draft-mode";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

const bebas = Bebas_Neue({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-bebas',
})
const breeserif = Bree_Serif({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-breeserif',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// const PreviewProvider = dynamic(() => import('@/components/PreviewProvider'))

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${bebas.variable} ${breeserif.variable} antialiased`}
      >
        {/* <SmoothScrolling>{children}</SmoothScrolling> */}
        {children}
        {(await draftMode()).isEnabled && (
        <>
          <SanityLive />
          <DisableDraftMode />
          <VisualEditing />
           {/* <VercelToolbar /> */}
        </>
      )}
      </body>
    </html>
  );
}
